services:
  vohnisca-api-gateway:
    image: vohnisca-api-gateway
    build:
      context: .
      dockerfile: vohnisca-api-gateway/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 